version: '3'
services:
  app:
    build: .
    ports:
      - "6767:6767"
    environment:
      - PORT=6767
    depends_on:
      - otel-collector

  otel-collector:
    #image: public.ecr.aws/aws-observability/aws-otel-collector:v0.39.0
    image: public.ecr.aws/h3e9h5g1/oodle/aws-otel-collector:v0.40.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - /tmp:/tmp
    environment:
      - OODLE_API_KEY=${OODLE_API_KEY}
      - OODLE_OTEL_METRICS_ENDPOINT=${OODLE_OTEL_METRICS_ENDPOINT}
      - OODLE_PROMETHEUS_ENDPOINT=${OODLE_PROMETHEUS_ENDPOINT}
    ports:
      - "4318:4318"       # OTLP HTTP receiver
      - "8125:8125/udp"   # StatsD receiver
      - "8888:8888"       # Prometheus metrics exposed by the collector